emerge --unmerge dev-haskell/cabal \
dev-haskell/xhtml \
dev-haskell/extensible-exceptions \
dev-haskell/deepseq \
dev-haskell/time \
dev-haskell/random \
dev-haskell/quickcheck \
dev-haskell/ansi-terminal \
dev-haskell/hostname \
dev-haskell/text \
dev-haskell/transformers \
dev-haskell/ansi-wl-pprint \
dev-haskell/xml \
dev-haskell/mtl \
dev-haskell/regex-base \
dev-haskell/regex-posix \
dev-haskell/test-framework \
dev-haskell/test-framework-quickcheck2 \
dev-haskell/blaze-builder \
dev-haskell/utf8-string \
dev-haskell/happy \
dev-haskell/utf8-light \
dev-haskell/language-javascript \
dev-haskell/hjsmin \
dev-haskell/ghc-paths \
app-text/docbook-xml-dtd \
dev-haskell/haddock \
dev-haskell/ghc-paths \
dev-haskell/attoparsec \
dev-haskell/cereal \
dev-haskell/parsec \
dev-haskell/system-filepath \
dev-haskell/base64-bytestring \
dev-haskell/hashable \
dev-haskell/transformers-base \
dev-haskell/tagged \
dev-haskell/failure \
dev-haskell/entropy \
dev-haskell/path-pieces \
dev-haskell/date-cache \
dev-haskell/unix-compat \
dev-haskell/zlib \
dev-haskell/dlist \
dev-haskell/primitive \
dev-haskell/tagsoup \
dev-haskell/binary \
dev-haskell/base-unicode-symbols \
dev-haskell/crypto-pubkey-types \
dev-haskell/cipher-aes \
dev-haskell/safe \
dev-haskell/split \
dev-haskell/file-embed \
dev-haskell/optparse-applicative \
dev-haskell/tar \
dev-haskell/syb \
dev-haskell/largeword \
dev-haskell/stm \
dev-haskell/unix-time \
dev-haskell/xml-types \
dev-haskell/ranges \
dev-haskell/cpu \
dev-haskell/semigroups \
dev-haskell/word8 \
dev-haskell/hinotify \
dev-haskell/stringsearch \
dev-haskell/byteorder \
dev-haskell/network \
dev-haskell/monad-control \
dev-haskell/vector \
dev-haskell/unordered-containers \
dev-haskell/crypto-api \
dev-haskell/blaze-markup \
dev-haskell/case-insensitive \
dev-haskell/shakespeare \
dev-haskell/data-default \
dev-haskell/void \
dev-haskell/fast-logger \
dev-haskell/system-fileio \
dev-haskell/asn1-data \
dev-haskell/pem \
dev-haskell/sha \
dev-haskell/mime-mail \
dev-haskell/email-validate \
dev-haskell/css-text \
dev-haskell/zlib-bindings \
dev-haskell/readargs \
dev-haskell/lifted-base \
dev-haskell/http-types \
dev-haskell/aeson \
dev-haskell/blaze-html \
dev-haskell/shakespeare-css \
dev-haskell/cryptohash \
dev-haskell/cryptocipher \
dev-haskell/yesod-routes \
dev-haskell/cookie \
dev-haskell/shakespeare-text \
dev-haskell/fsnotify \
dev-haskell/puremd5 \
dev-haskell/resource-pool \
dev-haskell/xss-sanitize \
dev-haskell/shakespeare-i18n \
dev-haskell/skein \
dev-haskell/simple-sendfile \
dev-haskell/socks \
dev-haskell/regex-compat \
dev-haskell/vault \
dev-haskell/basic-prelude \
dev-haskell/resourcet \
dev-haskell/shakespeare-js \
dev-haskell/hamlet \
dev-haskell/certificate \
dev-haskell/cprng-aes \
dev-haskell/pwstore-fast \
dev-haskell/classy-prelude \
dev-haskell/conduit \
dev-haskell/monad-logger \
dev-haskell/tls \
dev-haskell/pool-conduit \
dev-haskell/clientsession \
dev-haskell/wai-1.3.0.1
dev-haskell/blaze-builder-conduit \
dev-haskell/persistent \
dev-haskell/attoparsec-conduit \
dev-haskell/network-conduit \
dev-haskell/yaml \
dev-haskell/zlib-conduit \
dev-haskell/tls-extra \
dev-haskell/http-conduit \
dev-haskell/warp \
dev-haskell/persistent-template \
dev-haskell/xml-conduit \
dev-haskell/wai-logger \
dev-haskell/wai-extra \
dev-haskell/classy-prelude-conduit \
dev-haskell/authenticate \
dev-haskell/yesod-core \
dev-haskell/http-reverse-proxy \
dev-haskell/project-template \
dev-haskell/yesod-persistent \
dev-haskell/yesod-json \
dev-haskell/yesod-default \
dev-haskell/yesod-form \
dev-haskell/yesod-auth \
dev-haskell/yesod \
dev-db/postgresql-docs \
app-admin/eselect-postgresql \
dev-haskell/blaze-textual \
dev-db/postgresql-base \
dev-haskell/postgresql-libpq \
dev-haskell/postgresql-simple \
dev-haskell/persistent-postgresql \
dev-haskell/crypto-conduit \
dev-haskell/mime-types \
dev-haskell/http-date \
dev-haskell/wai-app-static \
dev-haskell/yesod-static \
dev-haskell/http-4000 \
dev-haskell/cabal-install \
dev-haskell/cabal-dev


