#!/bin/bash

emerge --unmerge dev-haskell/xhtml \
dev-haskell/haddock \
dev-haskell/unix-compat \
dev-haskell/mtl \
dev-haskell/quickcheck \
dev-haskell/test-framework \
dev-haskell/test-framework-quickcheck2 \
dev-haskell/extensible-exceptions \
dev-haskell/wai \
dev-haskell/vault \
dev-haskell/classy-prelude-conduit \
dev-haskell/xml-conduit \
dev-haskell/lifted-base \
dev-haskell/shakespeare-js-1.0.1 \
dev-haskell/hashable-1.1.2.5 \
dev-haskell/shakespeare-i18n-1.0.0.2 \
dev-haskell/resource-pool-0.2.1.1 \
dev-haskell/syb-0.3.7 \
dev-haskell/stringsearch-0.3.6.4 \
dev-haskell/pwstore-fast-2.3 \
dev-haskell/pem-0.1.1 \
dev-haskell/path-pieces-0.1.2 \
dev-haskell/warp-1.3.4.2 \
dev-haskell/tagsoup-0.12.8 \
dev-haskell/puremd5-2.1.2.1 \
dev-haskell/pool-conduit-0.1.0.3 \
dev-haskell/tagged-0.4.4 \
dev-haskell/base-unicode-symbols-0.2.2.4 \
dev-haskell/persistent-template \
dev-haskell/http-conduit \
dev-haskell/simple-sendfile \
dev-haskell/network-conduit \
dev-haskell/split \
dev-haskell/cereal \
dev-haskell/blaze-builder \
dev-haskell/monad-control \
dev-haskell/persistent \
dev-haskell/fsnotify \
dev-haskell/system-fileio \
dev-haskell/conduit \
dev-haskell/sha \
dev-haskell/yesod-form \
dev-haskell/blaze-markup- \
dev-haskell/clientsession \
dev-haskell/crypto-pubkey-types \
dev-haskell/http-types \
dev-haskell/entropy \
dev-haskell/hamlet \
dev-haskell/authenticate \
dev-haskell/project-template \
dev-haskell/wai-logger \
dev-haskell/shakespeare \
dev-haskell/system-filepath \
dev-haskell/certificate \
dev-haskell/hinotify \
dev-haskell/socks \
dev-haskell/http-reverse-proxy \
dev-haskell/wai-extra \
dev-haskell/attoparsec \
dev-haskell/classy-prelude \
dev-haskell/safe \
dev-haskell/asn1-data \
dev-haskell/basic-prelude \
dev-haskell/monad-logger \
dev-haskell/email-validate \
dev-haskell/zlib-conduit \
dev-haskell/unordered-containers \
dev-haskell/yesod-persistent \
dev-haskell/byteorder \
dev-haskell/tls-extra \
dev-haskell/void \
dev-haskell/tar \
dev-haskell/dlist \
dev-haskell/unix-time \
dev-haskell/tls \
dev-haskell/blaze-html \
dev-haskell/yesod-auth \
dev-haskell/cprng-aes \
dev-haskell/xml-types \
dev-haskell/ghc-paths \
dev-haskell/crypto-api \
dev-haskell/time \
dev-haskell/cryptohash \
dev-haskell/optparse-applicative \
dev-haskell/file-embed \
dev-haskell/failure \
dev-haskell/ranges \
dev-haskell/shakespeare-text \
dev-haskell/resourcet \
dev-haskell/transformers-base \
dev-haskell/semigroups \
dev-haskell/yesod-routes \
dev-haskell/date-cache \
dev-haskell/cpu \
dev-haskell/blaze-builder-conduit \
dev-haskell/aeson \
dev-haskell/shakespeare-css \
dev-haskell/base64-bytestring \
dev-haskell/yesod-json \
dev-haskell/cryptocipher \
dev-haskell/skein \
dev-haskell/fast-logger \
dev-haskell/yaml \
dev-haskell/case-insensitive \
dev-haskell/yesod-core \
dev-haskell/css-text \
dev-haskell/largeword \
dev-haskell/xss-sanitize \
dev-haskell/attoparsec-conduit \
dev-haskell/cookie \
dev-haskell/yesod-default \
dev-haskell/readargs \
dev-haskell/data-default \
dev-haskell/word8 \
dev-haskell/zlib-bindings \
dev-haskell/mime-mail \
dev-haskell/cipher-aes \
dev-haskell/language-javascript \
dev-haskell/hjsmin \
dev-haskell/utf8-light \
dev-haskell/postgresql-simple \
dev-haskell/blaze-textual \
dev-haskell/persistent-postgresql \
dev-haskell/postgresql-libpq \
dev-haskell/wai-app-static \
dev-haskell/http-date \
dev-haskell/crypto-conduit \
dev-haskell/yesod-static \
dev-haskell/mime-types \
dev-haskell/yesod-test \
dev-haskell/wai-test \
dev-haskell/hunit \
dev-haskell/filesystem-conduit \
dev-haskell/silently \
dev-haskell/hspec-expectations \
dev-haskell/setenv \
dev-haskell/html-conduit \
dev-haskell/hspec \
dev-haskell/tagstream-conduit \
dev-haskell/haskelldb-hdbc-mysql \
dev-haskell/haskelldb \
dev-haskell/hdbc \
dev-haskell/convertible \
dev-haskell/hdbc-mysql \
dev-haskell/haskelldb-hdbc \
dev-haskell/haskell-src-exts \
dev-haskell/uniplate \
dev-haskell/cmdargs \
dev-haskell/hoogle \
dev-haskell/texmath \
dev-haskell/parsec \
app-text/pandoc \
dev-haskell/citeproc-hs \
dev-haskell/highlighting-kate \
dev-haskell/hs-bibutils \
dev-haskell/temporary \
dev-haskell/pandoc-types \
dev-haskell/binary \
dev-haskell/json \
dev-haskell/regex-pcre-builtin \
dev-haskell/persistent-sqlite \
dev-haskell/cabal-install \
dev-haskell/cabal-dev \
dev-haskell/cabal \
dev-haskell/yesod